apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdemo-hello-deployment # 建議更改名稱
  namespace: default
  labels:
    app: nginxdemo-hello # 建議更改 Label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxdemo-hello # 建議更改 Label
  template:
    metadata:
      labels:
        app: nginxdemo-hello # 建議更改 Label
    spec:
      containers:
      - name: nginxdemo-hello
        image: nginxdemos/hello:plain-text # <-- 將這裡更改為新的映像檔
        ports:
        - containerPort: 80 # 這個映像檔監聽 80 埠
---
apiVersion: v1
kind: Service
metadata:
  name: nginxdemo-hello-service # 建議更改名稱
  namespace: default
spec:
  selector:
    app: nginxdemo-hello # 更改為與 Deployment 的 Label 相符
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # 服務的 80 埠會轉發到容器的 80 埠
  type: LoadBalancer