apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdemo-hello-deployment
  namespace: default
  labels:
    app: nginxdemo-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxdemo-hello
  template:
    metadata:
      labels:
        app: nginxdemo-hello
    spec:
      containers:
      - name: nginxdemo-hello
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxdemo-hello-service
  namespace: default
spec:
  selector:
    app: nginxdemo-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer