apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-deployment # 建議更改名稱
  namespace: default
  labels:
    app: echoserver # 建議更改 Label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echoserver # 建議更改 Label
  template:
    metadata:
      labels:
        app: echoserver # 建議更改 Label
    spec:
      containers:
      - name: echoserver
        image: k8s.gcr.io/echoserver:1.4 # <-- 將這裡更改為新的映像檔
        ports:
        - containerPort: 8080 # echoserver 應用程式監聽 8080 埠
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-service # 建議更改名稱
  namespace: default
spec:
  selector:
    app: echoserver # 更改為與 Deployment 的 Label 相符
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # 服務的 80 埠會轉發到容器的 8080 埠
  type: LoadBalancer